### ISSUE TITLE
UI - 'Add Communities' page

### ISSUE THREAD

**Issue by garrilla** [necsi/outreachapp-android#24]
Samsung Galaxy 7Edge - Android 8.0.0

Form doesn't extend over the width of the screen - looks broken, will turn some users back.

**Comment by studiofuga** [comment]
Hi Garrilla, can you test the apk here? 

https://drive.google.com/open?id=1ZMjOhF6iA5sZqg9PwBZgP3nRcxn38-zJ

Looking forward to get feedback from you.
Thanks

**Comment by garrilla** [comment]
Fixed.
